Prevent munging if FML mcmod.info is present in root of mod jar.
Fixes loading mods which have their mod_ class in their own package (e.g. Iron Chests, no longer fails with  java.lang.NoClassDefFoundError: mod_IronChest (wrong name: cpw/mods/ironchest/mod_IronChest) https://gist.github.com/c8b38490f7f1b1b47d14)